### ISSUE TITLE
Enhancement: Use 'glxinfo' instead of 'lspci' to get the active GPU

### ISSUE THREAD

**Issue by jgttech** [Nybkox/tmux-kanagawa#17]
### Describe the feature you'd like
There is a bug in the way this (i.e `./scripts/gpu_usage.sh`) detects GPU usage. The GPU usage detection uses `lspci` which is fine if you have one VGA device and only one. However, if you have more than one, like in a laptop (in my case, this is the case) you can't see the GPU utilization because checking for "NVIDIA" does not work if more than 1 VGA device is detected.

Instead switching it to this allows you to detect which device is active, not just what exists:

```bash
# ./scripts/gpu_usage.sh
gpu=$(glxinfo | grep -e OpenGL.renderer | awk '{print $4}')
```

### Describe risks you've considered
The only real risk to this change is that the information being detected requires the user to have `glxinfo` installed. However, this is more common than not, especially for Nvidia users (like myself). And doing detection for it is pretty easy.

### Describe alternatives you've considered
This was just an update idea to help the GPU detection work more reliably.

**Comment by Nybkox** [comment]
@jgttech, can you make a MR with the fix?

**Comment by jgttech** [comment]
> @jgttech, can you make a PR with the fix?

I was going to branch, add it, and open a PR but I don't have the permissions to do that. Do I need to do something special to create a PR with these changes?

**Comment by Nybkox** [comment]
@jgttech, you can fork the repo and create a PR from your fork.

**Comment by jgttech** [comment]
Thank you for that info. Here is the PR link (if you don't see the mention in the PR):
https://github.com/Nybkox/tmux-kanagawa/pull/18

**Comment by jgttech** [comment]
I had another idea, but idk if you want me to add it. If, in that same file, within the `main` function, I add this (after `RATE`):
```bash
name=$(glxinfo | grep "OpenGL renderer" | cut -d':' -f2 | sed -E 's/.*?(RTX|GTX|RX|R9|R7|R5|HD|Arc|UHD|Iris|HD Graphics) ([0-9]+[A-Za-z0-9]*).*/\1 \2/' | xargs)
```

And update the `gpu_label` to:

```bash
gpu_label=$(get_tmux_option "@kanagawa-gpu-usage-label" "GPU ($name)")
```

Then I get this on my TMUX status bar:
`GPU (RTX 3060)  ---%`

Which I also added support for AMD newer and older cards, as well as Intel GPUs.

**Comment by jgttech** [comment]
![Screenshot From 2024-11-02 17-41-43](https://github.com/user-attachments/assets/57b45e8f-b6ac-40fb-bfd4-033c87480de0)

Here is a sample of what it actually looks like in my setup with that last but added in.

**Comment by jgttech** [comment]
Accidentally closed it with a VIM shortcut when I thought my window context was changed, oops.
