### ISSUE TITLE
How to remove weather

### ISSUE THREAD

**Issue by Yair-Ziv1M** [Nybkox/tmux-kanagawa#19]
I just don't want the weather showing in the status bar

**Comment by Nybkox** [comment]
@Yair-Ziv1M, you can disable it in the config. Also you can turn on/off plugin via menu (prefix+T -> plugins)

**Comment by madsamjp** [comment]
You didn't really answer the question. HOW does one disable the weather (and other default plugins) in the config? I've tried this:
```
      set -g @kanagawa-show-battery false
      set -g @kanagawa-show-weather false
      set -g @kanagawa-show-network false
``` 
and it doesn't work

**Comment by Nybkox** [comment]
@madsamjp,
you can specify active plugins like this @kanagawa-plugins "battery".  Default active plugins are "battery network weather".
also you can enable/disable plugins via menu (prefix+T -> plugins -> M)
