### ISSUE TITLE
sync with upstream

### ISSUE THREAD

**Issue by leviszaboo** [Nybkox/tmux-kanagawa#8]
I suggest to merge some of the changes in the upstream dracula repository.
Specifically, the airport command is deprecated since macOS Sonoma 14.4 and will be removed in a future release, [this](https://github.com/Nybkox/tmux-kanagawa/commit/df75ea2a464788d87c4460b982793c9a300adbea) commit addresses this issue.
They also added some good new functionality.

**Comment by Nybkox** [comment]
You are welcome to create a PR :)

**Comment by Nybkox** [comment]
@leviszaboo  I ve sent an invite to become a collaborator.
